[build]
  base = "modern-portfolio"
  publish = "modern-portfolio/dist"
  command = "pnpm install && tsc -b && vite build"

[dev]
  command = "pnpm dev"
  port = 5173
  targetPort = 5173
  framework = "vite"

# Uncomment and configure if you use Netlify Functions
# [functions]
# directory = "modern-portfolio/netlify/functions"
